# Generated by Django 2.1.2 on 2020-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_detailes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(choices=[('1', 'Rapid Technologies LLC'), ('2', 'Rapid Group of Companies'), ('others', ' ')], default='1', max_length=6)),
                ('Division', models.CharField(choices=[('1', 'Staffing'), ('2', 'Training'), ('3', 'IT Services')], default='1', max_length=6)),
                ('Sector', models.CharField(choices=[('1', 'USA'), ('2', 'India')], default='1', max_length=6)),
                ('Phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
