# Generated by Django 2.1.2 on 2020-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200804_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Company',
            field=models.CharField(default='Rapid Group of Companies', max_length=6),
        ),
    ]
