# Generated by Django 2.1.2 on 2020-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200804_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Company',
            field=models.CharField(max_length=80),
        ),
    ]
