# Generated by Django 2.1.2 on 2020-08-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200804_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Division',
            field=models.CharField(choices=[('Staffing', 'Staffing'), ('Training', 'Training'), ('IT Services', 'IT Services')], default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Sector',
            field=models.CharField(choices=[('USA', 'USA'), ('India', 'India')], default='1', max_length=6),
        ),
    ]
