# Generated by Django 2.1.2 on 2020-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200804_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detailes',
            name='Fax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
