# Generated by Django 2.1.2 on 2020-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_company_detailes_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
