# Generated by Django 2.1.2 on 2020-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200805_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Division',
            field=models.TextField(choices=[('Staffing', 'Staffing'), ('Training', 'Training'), ('IT Services', 'IT Services')], default='IT Services', max_length=20),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Sector',
            field=models.TextField(choices=[('USA', 'USA'), ('India', 'India')], default='India', max_length=20),
        ),
    ]
