# Generated by Django 2.1.2 on 2020-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200805_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Sector',
            field=models.TextField(choices=[('USA', 'USA'), ('India', 'India')], default='2', max_length=20),
        ),
    ]
