# Generated by Django 2.1.2 on 2020-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200805_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Division',
            field=models.TextField(choices=[('Staffing', 'Staffing'), ('Training', 'Training'), ('IT Services', 'IT Services')], default='1', max_length=20),
        ),
    ]
