# Generated by Django 2.1.2 on 2020-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200805_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detailes',
            name='AddadditionalInformation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='AddressLine1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='AddressLine2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='City',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='EstimatedPayroll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='FederalID_EIN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='GST_Number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Industry',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='NAICS_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_Of_Employees',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_Internal_Employees',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_US_Citizens',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_card_consultants',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_consultants_on_CPT',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_consultants_on_H1B',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_consultants_on_OPT',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Number_of_consultants_on_other_visa',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='State',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Website',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='company_detailes',
            name='Zipcode',
            field=models.TextField(null=True),
        ),
    ]
