# Generated by Django 2.1.2 on 2020-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20200805_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Website',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
