# Generated by Django 2.1.2 on 2020-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200805_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
