# Generated by Django 2.1.2 on 2020-08-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20200805_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detailes',
            old_name='Website',
            new_name='website',
        ),
    ]
