# Generated by Django 2.1.2 on 2020-08-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20200805_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_detailes',
            name='website',
        ),
    ]
