# Generated by Django 2.1.2 on 2020-08-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_company_detailes_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detailes',
            old_name='Number_Of_Employees',
            new_name='Number_of_employees',
        ),
    ]
