# Generated by Django 2.1.2 on 2020-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20200805_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detailes',
            old_name='Number_of_employees',
            new_name='Number_employees',
        ),
    ]
