# Generated by Django 2.1.2 on 2020-08-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20200805_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detailes',
            old_name='Number_employees',
            new_name='NUMBER_employees',
        ),
    ]
