# Generated by Django 2.1.2 on 2020-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20200805_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
