# Generated by Django 2.1.2 on 2020-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20200805_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detailes',
            old_name='Number',
            new_name='Number_of_Employees',
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_US_Citizens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_card_consultants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_consultants_on_CPT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_consultants_on_H1B',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_consultants_on_OPT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Number_of_consultants_on_other_visa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
