# Generated by Django 2.1.2 on 2020-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_company_detailes_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detailes',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company_detailes',
            name='Website',
            field=models.TextField(null=True),
        ),
    ]
